### ISSUE TITLE
期待把声音加进去，再就是编码能不能另开一个线程，否则高分辨率卡的不行

### ISSUE THREAD

**Issue by Nishizawa1111** [hl1282456555/EasyFFMPEG#1]

**Comment by hl1282456555** [comment]
你可以试一试这个项目，里面有保存音频相关的代码，如果有需要的话可以自己merge一下。
https://github.com/hl1282456555/Streaming

开线程的话，有两个问题：
1、是机器的性能不够的话，高分辨率下缓存了太多帧数据会造成内存泄漏。
2、是ffmpeg是否支持多线程我暂时没有去测试。
