### ISSUE TITLE
supped mobile ?

### ISSUE THREAD

**Issue by LSLYWC** [hl1282456555/EasyFFMPEG#2]
android and ios?

**Comment by hl1282456555** [comment]
> 

not supported yet

**Comment by LSLYWC** [comment]
我自己编译一下FFMPEG安卓的库文件,接入到插件里，这个方案你觉可行嘛

**Comment by hl1282456555** [comment]
> 我自己编译一下FFMPEG安卓的库文件,接入到插件里，这个方案你觉可行嘛

确保ffmpeg库版本不要差太多（主要考虑库里头文件的兼容性）的话，ue部分的代码应该是可移植的
